# .readthedocs.yml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

build:
  os: ubuntu-20.04
  tools:
    python: "mambaforge-4.10"
  jobs:
    post_install:
      # Install numpy<v2 to avoid breaking docs. This is because the env has
      # pyspark installed, which requires numpy<2.
      - python -m pip install "numpy<2"
      # Install OpenJDK as Java backend in env to run PySpark examples in docs.
      - python -m pip install "install-jdk==1.1.0"
      - export JAVA_HOME=$(python -c "import jdk; jdk.install('11', vendor='temurin')")

# Build documentation in the docs/ directory with Sphinx
conda:
  environment: environment.yml

# Optionally set the version of Python and requirements required to build your docs
python:
  install:
    - method: pip
      path: .

sphinx:
  configuration: docs/source/conf.py

# Build documentation with MkDocs
#mkdocs:
#  configuration: mkdocs.yml

# Optionally build your docs in additional formats such as PDF and ePub
formats: []
