"""GeoPandas validation entry point for pandera.

Re-exports the full :mod:`pandera.pandas` public API plus
:class:`GeoDataFrameSchema` and :class:`GeoDataFrameModel`.

Importing this module runs :mod:`pandera.pandas` first (version checks, backends).
"""

from __future__ import annotations

import platform

import pandera.pandas as _pandas  # noqa: F401
from pandera import engines, errors, external_config
from pandera.api.geopandas import GeoDataFrameModel, GeoDataFrameSchema
from pandera.pandas import (
    BOOL,
    INT8,
    INT16,
    INT32,
    INT64,
    STRING,
    UINT8,
    UINT16,
    UINT32,
    UINT64,
    Bool,
    Category,
    Check,
    Column,
    Complex,
    Complex64,
    Complex128,
    DataFrameModel,
    DataFrameSchema,
    DataType,
    Date,
    DateTime,
    Decimal,
    Field,
    Float,
    Float16,
    Float32,
    Float64,
    Hypothesis,
    Index,
    Int,
    Int8,
    Int16,
    Int32,
    Int64,
    MultiIndex,
    Object,
    Parser,
    SeriesSchema,
    String,
    Timedelta,
    Timestamp,
    UInt,
    UInt8,
    UInt16,
    UInt32,
    UInt64,
    check,
    check_input,
    check_io,
    check_output,
    check_types,
    dataframe_check,
    dataframe_parser,
    dtypes,
    extensions,
    infer_schema,
    pandas_version,
    parser,
    typing,
)

__all__ = [
    "Bool",
    "Category",
    "Complex",
    "Complex64",
    "Complex128",
    "Date",
    "DataType",
    "DateTime",
    "Decimal",
    "Float",
    "Float16",
    "Float32",
    "Float64",
    "Int",
    "Int8",
    "Int16",
    "Int32",
    "Int64",
    "String",
    "Timedelta",
    "Timestamp",
    "UInt",
    "UInt8",
    "UInt16",
    "UInt32",
    "UInt64",
    "Object",
    "BOOL",
    "INT8",
    "INT16",
    "INT32",
    "INT64",
    "STRING",
    "UINT8",
    "UINT16",
    "UINT32",
    "UINT64",
    "pandas_version",
    "Check",
    "Parser",
    "check_input",
    "check_io",
    "check_output",
    "check_types",
    "Hypothesis",
    "DataFrameModel",
    "Field",
    "check",
    "dataframe_check",
    "parser",
    "dataframe_parser",
    "Column",
    "Index",
    "MultiIndex",
    "infer_schema",
    "DataFrameSchema",
    "SeriesSchema",
    "extensions",
    "typing",
    "dtypes",
]

if platform.system() != "Windows":
    from pandera.pandas import Complex256, Float128

    __all__.extend(["Complex256", "Float128"])

__all__.extend(["GeoDataFrameModel", "GeoDataFrameSchema"])
